"use client";
import {useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"https://rr-trader-1.onrender.com";
export default function Page(){
 const [invoice,setInvoice]=useState<any>(null),[tx,setTx]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function startPayment(){setBusy(true);setMsg("");try{const r=await fetch(API+"/api/v1/payments/crypto/invoices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({planId:"pro"})});const x=await r.json();if(!r.ok)throw new Error(x.message||x.error);setInvoice(x.invoice)}catch(e){setMsg(e instanceof Error?e.message:"Unable to create invoice")}finally{setBusy(false)}}
 async function verify(){if(!invoice||!tx)return;setBusy(true);setMsg("");try{const r=await fetch(API+"/api/v1/payments/crypto/invoices/"+invoice.id+"/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({txHash:tx})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Payment not verified");setInvoice(x.invoice);setMsg("Payment verified on BNB Smart Chain. Access can now be activated.")}catch(e){setMsg(e instanceof Error?e.message:"Payment verification failed")}finally{setBusy(false)}}
 const qr=invoice?("https://api.qrserver.com/v1/create-qr-code/?size=320x320&data="+encodeURIComponent("ethereum:"+invoice.receiveAddress+"?chainId=56&value="+invoice.amount)): "";
 return <main className="shell"><header className="page-head"><div><span className="eyebrow">MEMBERSHIP</span><h1>Premium Access</h1><p className="muted">3-day trial, then secure crypto checkout with on-chain verification.</p></div></header>
 <section className="pricing"><div className="price card"><span className="eyebrow">TRIAL</span><h2>3 Days Free</h2><p className="muted">Explore the premium workspace before subscribing.</p><span className="pill">2 markets</span></div><div className="price card featured"><span className="eyebrow">PREMIUM</span><h2>29 USDT</h2><p className="muted">Pay USDT on BNB Smart Chain (BEP20).</p><button className="primary" onClick={startPayment} disabled={busy}>{busy?"Creating...":"Pay with USDT"}</button></div></section>
 {invoice&&<section className="card" style={{marginTop:20,maxWidth:900}}><span className="eyebrow">BEP20 CHECKOUT</span><h2>Send exactly {invoice.amount} USDT</h2><p className="muted">Network: BNB Smart Chain · Token: USDT · Invoice expires in 30 minutes.</p><div style={{display:"grid",gridTemplateColumns:"320px 1fr",gap:24,alignItems:"center"}}><img src={qr} alt="BEP20 payment QR" width={320} height={320}/><div><p className="muted">Receive address</p><div className="card" style={{wordBreak:"break-all"}}>{invoice.receiveAddress}</div><button className="button" onClick={()=>navigator.clipboard?.writeText(invoice.receiveAddress)}>Copy address</button><p className="muted">After sending, paste the transaction hash below. The server verifies recipient, contract, amount and confirmations directly on BNB Smart Chain.</p><input className="controls" style={{width:"100%"}} placeholder="0x transaction hash" value={tx} onChange={e=>setTx(e.target.value)}/><button className="primary" style={{marginTop:10}} onClick={verify} disabled={busy||!tx}>{busy?"Checking...":"Verify payment"}</button></div></div>{msg&&<p className="muted" style={{marginTop:15}}>{msg}</p>}</section>}
 </main>
}