import type {Candle,Direction,SetupState,Signal} from "@quantedge/shared";
const ema=(a:number[],n:number)=>{if(a.length<n)return 0;const k=2/(n+1);let e=a.slice(0,n).reduce((x,y)=>x+y,0)/n;for(const v of a.slice(n))e=v*k+e*(1-k);return e};
export function analyze(symbol:string,candles:Candle[],minConfidence=85):Omit<Signal,"exchange"|"market"|"createdAt">{const closes=candles.map(x=>x.close);if(candles.length<60)return {symbol,direction:"NO_TRADE",setupState:"NO_TRADE",confidence:0,entry:null,stopLoss:null,targets:[],riskReward:0,reasons:["Insufficient candle history"],invalidations:["Need at least 60 candles"]};
const last=candles.at(-1)!,e20=ema(closes,20),e50=ema(closes,50),recent=candles.slice(-20),prior=candles.slice(-40,-20),recentHigh=Math.max(...recent.map(x=>x.high)),recentLow=Math.min(...recent.map(x=>x.low)),priorHigh=Math.max(...prior.map(x=>x.high)),priorLow=Math.min(...prior.map(x=>x.low)),avgVol=recent.reduce((s,x)=>s+x.volume,0)/recent.length;
let direction:Direction="NO_TRADE";let score=0;const reasons:string[]=[];const invalidations:string[]=[];
const bull=last.close>e20&&e20>e50, bear=last.close<e20&&e20<e50;
if(bull){direction="LONG";score+=25;reasons.push("EMA trend aligned bullish")}else if(bear){direction="SHORT";score+=25;reasons.push("EMA trend aligned bearish")}else invalidations.push("Higher trend alignment is mixed");
const breakout=last.close>priorHigh&&last.close>=recentHigh*0.999;const breakdown=last.close<priorLow&&last.close<=recentLow*1.001;
if(direction==="LONG"&&breakout){score+=25;reasons.push("Price broke the prior structure high")}else if(direction==="SHORT"&&breakdown){score+=25;reasons.push("Price broke the prior structure low")}else invalidations.push("Trigger structure has not broken");
if(last.volume>avgVol*1.2){score+=15;reasons.push("Volume expansion confirms the move")}else invalidations.push("Volume expansion is weak");
const body=Math.abs(last.close-last.open),range=Math.max(last.high-last.low,Number.EPSILON);if(body/range>=0.55){score+=10;reasons.push("Trigger candle has decisive body")}else invalidations.push("Trigger candle lacks conviction");
const confidence=Math.min(100,score+10);const triggered=score>=75&&confidence>=minConfidence&&(direction==="LONG"?breakout:direction==="SHORT"?breakdown:false);const setupState:SetupState=triggered?"TRIGGERED":direction==="NO_TRADE"?"NO_TRADE":"FORMING";
if(!triggered)return {symbol,direction:"NO_TRADE",setupState,confidence,entry:null,stopLoss:null,targets:[],riskReward:0,reasons:direction==="NO_TRADE"?reasons:["Setup is forming; trigger not confirmed"],invalidations};
const risk=Math.max(last.close*0.002,Math.abs(last.close-(direction==="LONG"?recentLow:recentHigh)));const stopLoss=direction==="LONG"?last.close-risk:last.close+risk;const targets=direction==="LONG"?[last.close+risk,last.close+risk*2,last.close+risk*3]:[last.close-risk,last.close-risk*2,last.close-risk*3];
return {symbol,direction,setupState,confidence,entry:last.close,stopLoss,targets,riskReward:2,reasons,invalidations}}