"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"";
const nav=[["Overview","/dashboard","O"],["Markets","/markets","M"],["Scanner","/scanner","S"],["Signals","/signals","T"],["Charts","/charts?symbol=BTCUSDT","C"],["Watchlist","/watchlist","W"]];
const coins=["BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT"];
export default function Page(){
 const[data,setData]=useState<any[]>([]);
 useEffect(()=>{Promise.all(coins.map(async symbol=>{try{return await fetch(API+"/api/v1/markets/"+symbol+"?market=futures").then(r=>r.json())}catch{return {symbol,last:0,change24h:0,volume24h:0}}})).then(setData)},[]);
 return 
  <div className="main">
   <section className="hero"><div><span className="eyebrow">QUANTEDGE / OVERVIEW</span><h1>Trade when the setup is ready.</h1><p className="muted hero-copy">A premium command center for live markets, setup detection, validated signals and disciplined risk. No forced trades. No noise.</p></div><div className="actions"><Link className="button" href="/markets">Explore Markets</Link><Link className="primary" href="/scanner">Run Scanner →</Link></div></section>
   <section className="stats"><div className="card kpi"><div className="kpi-top"><span>ENGINE STATUS</span><span>LIVE</span></div><strong className="positive">ONLINE</strong><small className="muted">Market data layer connected</small></div><div className="card kpi"><div className="kpi-top"><span>SETUPS</span><span>REAL-TIME</span></div><strong>SETUP FIRST</strong><small className="muted">Waits for structure confirmation</small></div><div className="card kpi"><div className="kpi-top"><span>MARKETS</span><span>BINANCE</span></div><strong>SPOT + FUTURES</strong><small className="muted">Multi-market intelligence</small></div><div className="card kpi"><div className="kpi-top"><span>RISK MODE</span><span>ACTIVE</span></div><strong>PROTECTED</strong><small className="muted">Entry, invalidation & targets</small></div></section>
   <section className="dashboard-grid"><div className="card section-card"><div className="section-head"><div><h2>Active Trade Setups</h2><span>Only opportunities currently forming</span></div><Link className="button" href="/signals">View Signals</Link></div><div className="setup-empty"><div><div className="setup-ring">◎</div><h3>No validated setup yet</h3><p className="muted">The engine will surface a trade only when market structure, momentum and confirmation align.</p><Link className="primary" href="/scanner">Scan Now</Link></div></div></div>
   <div className="card section-card"><div className="section-head"><div><h2>Market Watch</h2><span>Top tracked pairs</span></div><Link href="/markets" className="muted">All →</Link></div><div className="watch-list">{data.slice(0,5).map(x=><div className="watch-row" key={x.symbol}><Link href={"/charts?symbol="+x.symbol}>{x.symbol?.replace("USDT","")} <small>/USDT</small></Link><small>{x.last||"—"}</small><b className={Number(x.change24h)>=0?"positive":"negative"}>{x.change24h==null?"—":Number(x.change24h).toFixed(2)+"%"}</b></div>)}</div></div></section>
   <section className="card section-card market-table"><div className="section-head"><div><h2>Live Market Overview</h2><span>Click any asset to open its chart</span></div><Link className="button" href="/charts?symbol=BTCUSDT">Open Chart</Link></div><div className="table-wrap"><table className="table"><thead><tr><th>Asset</th><th>Last Price</th><th>24h Change</th><th>24h Volume</th><th>Action</th></tr></thead><tbody>{data.map(x=><tr key={x.symbol}><td><Link className="coin-link" href={"/charts?symbol="+x.symbol}><span className="coin-dot">{x.symbol?.slice(0,1)}</span>{x.symbol}</Link></td><td>{x.last||"—"}</td><td className={Number(x.change24h)>=0?"positive":"negative"}>{x.change24h==null?"—":Number(x.change24h).toFixed(2)+"%"}</td><td>{x.volume24h?Number(x.volume24h).toLocaleString():"—"}</td><td><Link href={"/charts?symbol="+x.symbol}>Chart →</Link></td></tr>)}</tbody></table></div></section>
  
}